(deftheme my-theme
  "Created 2021-07-22.")

(custom-theme-set-faces
 'my-theme
 '(default ((t (:inherit nil :extend nil :stipple nil :background "gray14" :foreground "gray94" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "nil" :family "Monaco"))))
 '(cursor ((t (:background "forest green"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "medium purple" :weight bold))))
 '(homoglyph ((t (:foreground "DarkOrange1" :weight bold))))
 '(minibuffer-prompt ((t (:foreground "cyan3"))))
 '(highlight ((t (:underline (:style line :color foreground-color) :foreground "#111" :background "SeaGreen2"))))
 '(region ((t (:extend t :foreground "#f6f3e8" :background "#444444"))))
 '(shadow ((t (:foreground "light slate gray"))))
 '(secondary-selection ((t (:extend t :foreground "#f6f3e8" :background "#333366"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "MediumOrchid1"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :foreground "cyan"))))
 '(font-lock-comment-face ((t (:foreground "cyan"))))
 '(font-lock-constant-face ((t (:foreground "royal blue"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#cae682"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#8ac6f2"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "chartreuse3"))))
 '(font-lock-type-face ((t (:foreground "SpringGreen3" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "chartreuse2"))))
 '(font-lock-warning-face ((t (:foreground "OrangeRed2"))))
 '(button ((t (:foreground "#f6f3e8" :background "#333333"))))
 '(link ((t (:foreground "turquoise2" :underline t))))
 '(link-visited ((t (:foreground "purple3" :underline t))))
 '(fringe ((t (:inherit default))))
 '(header-line ((t (:foreground "#e7f6da" :background "#303030"))))
 '(tooltip ((t (:inherit variable-pitch :background "light gray" :foreground "black"))))
 '(mode-line ((t (:foreground "#f6f3e8" :background "#444444"))))
 '(mode-line-buffer-id ((t (:foreground "dark orange" :weight bold))))
 '(mode-line-emphasis ((t (:foreground "MediumOrchid3" :weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#857b6f" :background "#444444"))))
 '(isearch ((t (:background "#343434" :foreground "DarkOrange2"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "#a0a8b0" :background "#384048"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
;; org header theme from https://emacs.stackexchange.com/questions/7429/how-to-customize-org-mode-indentation
 '(org-level-1 ((t (:inherit variable-pitch :foreground "#cb4b16" :weight bold :height 1.3))))
 '(org-level-2 ((t (:inherit variable-pitch :foreground "#859900" :weight bold :height 1.2))))
 '(org-level-3 ((t (:inherit variable-pitch :foreground "#268bd2" :weight bold :height 1.15))))
 '(org-level-4 ((t (:inherit variable-pitch :foreground "#b58900" :weight bold :height 1.1))))
 '(org-level-5 ((t (:inherit variable-pitch :foreground "#2aa198" :weight bold))))
 '(org-level-6 ((t (:inherit variable-pitch :foreground "#6c71c4" :weight bold))))
 '(org-level-7 ((t (:inherit variable-pitch :foreground "#d33682" :weight bold))))
 '(org-level-8 ((t (:inherit variable-pitch :foreground "#dc322f" :weight bold)))))
 '(evil-ex-substitute-matches ((t (:inherit variable-pitch :foreground "RoyalBlue3" :weight bold))))


(provide-theme 'my-theme)
